apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: rosskukulinski/sample-app:rc102
          env:
            - name: NSOLID_APPNAME
              value: sample-app
            - name: NSOLID_COMMAND
              value: "storage.nsolid:9001"
            - name: NSOLID_DATA
              value: "storage.nsolid:9002"
            - name: NSOLID_BULK
              value: "storage.nsolid:9003"
            - name: NSOLID_TAGS
              value: "nsolid-v2.0.0"
            - name: PORT
              value: "4444"
          ports:
            - containerPort: 4444
              name: sample-app
