apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: rosskukulinski/myapp:v2
          env:
            - name: NSOLID_APPNAME
              value: myapp
            - name: NSOLID_HUB
              value: "nsolid-registry.nsolid:4001"
            - name: NSOLID_SOCKET
              value: "8000"
            - name: NSOLID_TAGS
              value: "nsolid-v1.3.1"
            - name: PORT
              value: "4444"
          ports:
            - containerPort: 4444
              name: myapp
            - containerPort: 8000
              name: nsolid
